### PR TITLE
Add default introductory code example

### PR DESCRIPTION
**Pull request by kytrinyx**
Instead of having logic for a fallback in the backend, we're choosing a
default for the snippet file.

For tracks that have core exercises, we pick the first core exercise.
For tracks without these, we pick the first exercise listed in the config.

Note that we're aiming for 10 lines and a max-width of 40 columns.
This solution has 14 lines and a max-width of 46, so we may want to adjust it.

See https://github.com/exercism/meta/issues/89

### CODE REVIEW

**Comment by kytrinyx** [comment]
I think the solution here is to remove the conditionals and make this a traditional hard-coded "Hello, World!" code snippet.

If anyone wants to submit something, I'd love to accept that instead of merging this.

**Comment by MarkSchwarzmann** [comment]
The simplest "Hello world" program would be:

```
void main() {
	import std.stdio;
	writeln("Hello world");
}
```

**Comment by kytrinyx** [comment]
Thanks @markschw I'll go ahead and do that.

**Comment by kytrinyx** [comment]
Another option is to remove the `unittest` section and rename the parameter to `s` instead of `name`. It's not a great name, admittedly, but it does leave us with a bit more of the language syntax to look at:

```
module helloworld;

import std.format;

string hello(const char[] s = "World") {
    return format("Hello, %s!", s);
}
```

What do you think @markschw?

**Comment by markschw** [comment]
Well, the current example does show more of the language syntax, but:
1. It doesn't compile (no main() function) so you can't plainly run it.
2. It looks somewhat like the traditional "Hello world" program but it does something different. This might be confusing to someone not familiar with the language.

I'm not sure what should be the level of sophistication of these introductory examples, so it's difficult for me to say if it's appropriate or not.

**Comment by kytrinyx** [comment]
> It doesn't compile

I think that's fine, as long as it is valid code.

This is not meant to be particularly sophisticated, and it's only intended to give people a visual impression of what the language looks like on the main page for the D track on the new exercism site that we're working on: https://v2.exercism.io/tracks/d

**Comment by ohdatboi** [comment]
It is possible to have both `main()` and `unittest` in the same file.

IMO `format()` is not a part of the language, but standard library, so it can be replaced with the concatenation operator `~`. 
`const char[]` can be just replaced with `string`

```D
void main(string[] args) {
	if(args.length < 2)
		writeln(hello);
	else
		writeln(hello(args[1]));
}

auto hello(string name = "World") {
	return "Hello, " ~ name ~ "!";
}

unittest {
	assert(hello() == "Hello, World!");
	assert(hello("Alice") == "Hello, Alice!");
	assert(hello("Bob") == "Hello, Bob!");
	assert(hello("") == "Hello, !");
}
```

Run it with:
```
$ dmd -run hello.d Me
Hello, me!
```

Execute unittests:
```
$ dmd -unittest -run hello.d
```

**Comment by kytrinyx** [comment]
> It is possible to have both main() and unittest in the same file.

Thanks @ohdatboi, the thing is... we're not really optimizing for runnability here. What we're trying to do is make a small example that is correct code and shows off what the language looks like, in 10 lines or less, and 40 characters wide or less.

I think it's perfectly fine if this can't be copy/pasted and run on the command-line.

**Comment by ohdatboi** [comment]
>  What we're trying to do is make a small example that is correct code and shows off what the language looks like, in 10 lines or less, and 40 characters wide or less.

What about code samples on the [dlang.org](https://dlang.org)? Some of them are pretty nice and short (like "Compute average line length for stdin")

**Comment by kytrinyx** [comment]
> What about code samples on the dlang.org?

Those are nice. "Compute average line length for stdin" is 47 columns wide at it's widest, though, so it's not going to fit directly.

We'd also have to check what the license is on it, and I'm not sure how we would provide attribution.

**Comment by ohdatboi** [comment]
> "Compute average line length for stdin" is 47 columns wide at it's widest, though, so it's not going to fit directly.

Can be easily modified to 36:

```D
void main()
{
    import std.range, std.stdio;

    auto sum = 0.0;
    auto count = stdin.byLine
        .tee!(l => sum += l.length)
        .walkLength;

    writeln("Average line length: ",
        count ? sum / count : 0);
}
```

> We'd also have to check what the license is on it, and I'm not sure how we would provide attribution.

dlang.org's [repository](https://github.com/dlang/dlang.org) is under BSL-1.0.

**Comment by kytrinyx** [comment]
> Can be easily modified to 36:

Excellent. That would definitely be a good choice. Let me look at the license and see if I can figure out what we would have to do in order to use the example.

**Comment by kytrinyx** [comment]
ok, so for the BSL this is the summary:

> A simple permissive license only requiring preservation of copyright and license notices for source (and not binary) distribution.

We would need to keep the boost license in the d repo with some notation that it's about the snippet.

To be honest, I would rather write our own snippet than have to deal with the extra licensing thing.

**Comment by markschw** [comment]
In that case, the example you posted before seems good enough to me.

**Comment by kytrinyx** [comment]
@markschw You mean this:

```
module helloworld;

import std.format;

string hello(const char[] s = "World") {
    return format("Hello, %s!", s);
}
```

If so, I'll go ahead and update this pull request and merge it.

**Comment by markschw** [comment]
Yup.

**Comment by kytrinyx** [comment]
Alrighty, updated.

Thank you @markschw and @ohdatboi for helping think this one through!

**Pull request merged**
